# IMPORTANTE: Coloque o nome da sua organização do SonarCloud aqui
sonar.organization=leandroyyy
sonar.projectKey=Leandroyyy_targeting-service
sonar.projectName=Targeting Service

# Diretórios que contêm o código fonte
sonar.sources=.

# Exclusões de arquivos que não precisam ser analisados pelo Sonar
sonar.exclusions=infra/**, k8s/**, **/*.yml

