name: Security

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # O Sonar exige o histórico completo do Git para análise correta (blame)

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # O GitHub Action precisa desse token nativo para analisar PRs
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

